---
version: "3"

volumes:
  media:
  static:
  pgdata:

services:
  web:
    build: .
    restart: always
    working_dir: /code
    command: bash cmd.sh run
    volumes:
      - media:/code/project/media
      - static:/code/project/staticfiles
    env_file: .env
    expose:
      - 8000
    depends_on:
      - db
      - memcached

  static:
    image: nginx:alpine
    restart: always
    volumes:
      - static:/nginx/static
      - media:/nginx/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - web

  db:
    image: postgres:13.1
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env

  memcached:
    image: memcached:latest
    restart: always
