# Generated by Django 3.1.4 on 2021-02-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('canonical_url', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('author', models.CharField(blank=True, max_length=127)),
                ('uid', models.PositiveIntegerField(unique=True)),
                ('source', models.CharField(max_length=50)),
                ('source_id', models.CharField(max_length=255)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('recipes', models.ManyToManyField(related_name='tokens', related_query_name='token', through='data.RecipeToken', to='data.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipetoken',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.token'),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=128)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipes', related_query_name='recipe', to='data.Tag'),
        ),
    ]
