# Generated by Django 3.1.4 on 2021-02-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210216_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='title',
            field=models.CharField(max_length=127, unique=True),
        ),
    ]
