# Generated by Django 3.1.4 on 2021-02-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20210222_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('favicon', models.CharField(max_length=256)),
            ],
        ),
    ]
