# Generated by Django 3.1.4 on 2021-02-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_source'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recipetoken',
            index=models.Index(fields=['recipe'], name='data_recipe_recipe__e3073d_idx'),
        ),
    ]
