# Generated by Django 3.1.4 on 2021-03-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210304_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='source_id',
            new_name='source_raw_id',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', related_query_name='recipe', to='data.source'),
        ),
    ]
