# Generated by Django 3.1.4 on 2021-03-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20210304_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='length',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
