# Generated by Django 3.1.4 on 2021-03-24 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_recipe_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTokenFrequencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_title', models.BooleanField()),
                ('tf', models.FloatField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.recipe')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.token')),
            ],
        ),
    ]
