# Generated by Django 3.1.4 on 2021-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_recipetokenfrequencies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeTokenFrequencies',
            new_name='RecipeTokenFrequency',
        ),
    ]
