# Generated by Django 3.1.4 on 2021-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20210324_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetokenfrequency',
            name='tf',
            field=models.IntegerField(),
        ),
    ]
